Repository Iridium-Development/IridiumSkyblock, pull requests merged in 2021-08, with the labels that each got.

#337 Make changeable spawn world
  src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
  src/main/java/com/iridium/iridiumskyblock/utils/PlayerUtils.java
Labels: enhancement

#341 Anti-Island Member Kick
  src/main/java/com/iridium/iridiumskyblock/commands/PrivateCommand.java
Labels: bug, invalid

#350 Shorten relocation code & Add comments
  build.gradle.kts
Labels: enhancement

#351 Add cooldown for interaction messages
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
Labels: enhancement

#348 Add Island Regen and Delete Settings
  src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandRegenGUI.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: enhancement

#353 Clear database entries with island deletion
  src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: bug, enhancement

#356 Fix obsidian bucket message
  src/main/java/com/iridium/iridiumskyblock/listeners/BucketListener.java
Labels: bug

#357 Add missing placeholder abbreviations
  src/main/java/com/iridium/iridiumskyblock/gui/BankGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/BoostersGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/UpgradesGUI.java
Labels: bug

#355 Use PaperLib for Async Teleport Player
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
  src/main/java/com/iridium/iridiumskyblock/utils/PlayerUtils.java
Labels: enhancement

#374 Add proper subcommand system, Cleanup CommandManager code
  build.gradle.kts
  src/main/java/com/iridium/iridiumskyblock/commands/BankCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/Command.java
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
  src/main/java/com/iridium/iridiumskyblock/commands/bank/GiveCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/bank/RemoveCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/bank/SetCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Commands.java
Labels: enhancement

#358 Use generics when possible
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/gui/UpgradesGUI.java
Labels: enhancement, needs testing
