Repository Iridium-Development/IridiumSkyblock, pull requests merged in 2021-07, with the labels that each got.

#231 Fix ForeignIslandTableManager NullPointerException
  src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/ForeignIslandTableManager.java
Labels: bug

#230 Fix bank command color issues
  src/main/java/com/iridium/iridiumskyblock/commands/DepositCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/WithdrawCommand.java
Labels: bug

#229 Add support for inventory title placeholders
  src/main/java/com/iridium/iridiumskyblock/configs/inventories/NoItemGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/BankGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/BiomeGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/BoostersGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/ConfirmationGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/GUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/InventoryConfigGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/InvitesGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandRanksGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandTopGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/LogsGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MembersGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MissionsGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/PermissionsGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/RewardsGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/SchematicGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/ShopOverviewGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/TrustedGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/UpgradesGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/VisitGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/WarpsGUI.java
Labels: enhancement

#235 Fix inventory clicks activating guis
  src/main/java/com/iridium/iridiumskyblock/listeners/InventoryClickListener.java
Labels: bug

#239 Fix topgui backgrounds clear
  src/main/java/com/iridium/iridiumskyblock/gui/IslandTopGUI.java
Labels: bug

#238 Cache
  src/main/java/com/iridium/iridiumskyblock/Cache.java
  src/main/java/com/iridium/iridiumskyblock/database/Island.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: bug, enhancement

#240 Add coal ore to the generator
  src/main/java/com/iridium/iridiumskyblock/configs/Upgrades.java
Labels: enhancement

#250 Fix typo in plugin description
  src/main/resources/plugin.yml
Labels: bug

#246 Placeholder support to island chat
  src/main/java/com/iridium/iridiumskyblock/api/UserChatToggleEvent.java
  src/main/java/com/iridium/iridiumskyblock/commands/ChatCommand.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerChatListener.java
Labels: enhancement

#255 Add Block limit upgrade
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/configs/Border.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/configs/Upgrades.java
  src/main/java/com/iridium/iridiumskyblock/gui/InvitesGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandTopGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MembersGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MissionsGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/SchematicGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/TrustedGUI.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
  src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
  src/main/java/com/iridium/iridiumskyblock/upgrades/BlockLimitUpgrade.java
Labels: enhancement

#267 Make shop sells only with right click
  src/main/java/com/iridium/iridiumskyblock/gui/ShopCategoryGUI.java
Labels: bug

#268 Fix unsupported biome selection
  src/main/java/com/iridium/iridiumskyblock/commands/BiomeCommand.java
  src/main/java/com/iridium/iridiumskyblock/gui/BiomeGUI.java
Labels: bug

#269 Fix ore generator NullPointerException
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockFormListener.java
  src/main/java/com/iridium/iridiumskyblock/utils/RandomAccessList.java
Labels: bug

#271 Fix mission issues with ores in the 1.17
  src/main/java/com/iridium/iridiumskyblock/configs/Missions.java
Labels: bug

#270 Fix entity spawning on foreign islands
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
Labels: bug

#274 Clean up .gitignore
  .gitignore
Labels: enhancement

#273 Fix entity spawning message
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
Labels: bug

#272 Add Plugin config load event
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/api/IridiumSkyblockReloadEvent.java
Labels: enhancement

#258 Fix world issues
  src/main/java/com/iridium/iridiumskyblock/api/IridiumSkyblockAPI.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockFormListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockGrowListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockPistonListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EnchantItemListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityDamageListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityDeathListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/ItemCraftListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerFishListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerRespawnListener.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: bug

#296 Make confirmation gui yes-no item slots changeable
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/configs/Inventories.java
  src/main/java/com/iridium/iridiumskyblock/gui/ConfirmationGUI.java
Labels: bug, enhancement

#285 Add Obsidian -> Lava Bucket
  src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BucketListener.java
Labels: enhancement

#299 Fix events
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockExplodeListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockFormListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockPistonListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BucketListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityDamageListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityExplodeListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityPickupItemListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EntitySpawnListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/InventoryClickListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerDropItemListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerPortalListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerTeleportListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/SpawnerSpawnListener.java
Labels: bug, enhancement

#307 Fix database XMaterial loading
  src/main/java/com/iridium/iridiumskyblock/database/types/XMaterialType.java
  src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
Labels: bug

#306 Fix void teleport
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
Labels: bug

#301 Make shop item names configurable
  src/main/java/com/iridium/iridiumskyblock/configs/Shop.java
  src/main/java/com/iridium/iridiumskyblock/shop/ShopItem.java
  src/main/java/com/iridium/iridiumskyblock/shop/ShopManager.java
Labels: bug, confirmed

#293 Make blockvaluesgui pageable+slotable
  src/main/java/com/iridium/iridiumskyblock/commands/BlockValueCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/BlockValues.java
  src/main/java/com/iridium/iridiumskyblock/database/Island.java
  src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java
Labels: bug, enhancement

#292 Visitors, IslandBans, and new events
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/PermissionType.java
  src/main/java/com/iridium/iridiumskyblock/PlaceholderBuilder.java
  src/main/java/com/iridium/iridiumskyblock/api/IslandEnterEvent.java
  src/main/java/com/iridium/iridiumskyblock/api/IslandLeaveEvent.java
  src/main/java/com/iridium/iridiumskyblock/commands/BanCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
  src/main/java/com/iridium/iridiumskyblock/commands/ExpelCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PrivateCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnBanCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Commands.java
  src/main/java/com/iridium/iridiumskyblock/configs/Inventories.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/configs/Permissions.java
  src/main/java/com/iridium/iridiumskyblock/database/Island.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBan.java
  src/main/java/com/iridium/iridiumskyblock/database/User.java
  src/main/java/com/iridium/iridiumskyblock/gui/BansGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/VisitorsGUI.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerJoinQuitListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerPortalListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerRespawnListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerTeleportListener.java
  src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: api, enhancement

#319 Fix projectile message spam
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityDamageListener.java
Labels: bug

#309 Visitors, IslandBans, and new events (#292)
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/PermissionType.java
  src/main/java/com/iridium/iridiumskyblock/PlaceholderBuilder.java
  src/main/java/com/iridium/iridiumskyblock/commands/BanCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BankCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BlockValueCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BorderCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
  src/main/java/com/iridium/iridiumskyblock/commands/DeleteWarpCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/DemoteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/DepositCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/EditWarpCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/ExpelCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/FlyCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/InfoCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/InviteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/JoinCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/KickCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/LevelCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/MissionCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PrivateCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PromoteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/RegenCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/ShopCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/TransferCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/TrustCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnBanCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnInviteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnTrustCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UpgradesCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/VisitCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/WarpsCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/WithdrawCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Commands.java
  src/main/java/com/iridium/iridiumskyblock/configs/Inventories.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/configs/Permissions.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBan.java
  src/main/java/com/iridium/iridiumskyblock/database/User.java
  src/main/java/com/iridium/iridiumskyblock/gui/BansGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/VisitorsGUI.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerJoinQuitListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerPortalListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerRespawnListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerTeleportListener.java
  src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
  src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
Labels: enhancement

#266 Fix vehicle breaking without permission
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/listeners/VehicleDamageListener.java
Labels: bug

#304 Fix obsidian to lava thing
  src/main/java/com/iridium/iridiumskyblock/listeners/BucketListener.java
Labels: bug, enhancement

#332 Bump ormlite-jdbc & jetbrains-annotations, Chance dependency format
  build.gradle.kts
Labels: enhancement

#330 add option to disable patreon message
  src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerJoinQuitListener.java
Labels: bug
