Repository Iridium-Development/IridiumSkyblock, pull requests merged in 2021-11, with the labels that each got.

#389 Island name
  src/main/java/com/iridium/iridiumskyblock/DataConverter.java
  src/main/java/com/iridium/iridiumskyblock/commands/CreateCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/RenameCommand.java
  src/main/java/com/iridium/iridiumskyblock/database/Island.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandCreateGUI.java
  src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/IslandTableManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/TableManager.java
  src/main/resources/patch_2_mysql.sql
  src/main/resources/patch_2_sqlite.sql
Labels: bug

#491 Fix mushroom schematic generate nothing.
  src/main/resources/mushroom.schem
Labels: bug

#445 Optimization: Use Async Task Recalculate Command
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: enhancement, help wanted

#492 Migrate to a safe OrmLite version
  build.gradle.kts
Labels: bug

#496 Add offline player support to bank commands
  src/main/java/com/iridium/iridiumskyblock/commands/bank/GiveCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/bank/RemoveCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/bank/SetCommand.java
Labels: enhancement

#424 Added ExtraValueCommand
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/iridium/iridiumskyblock/commands/ExtraValueCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Commands.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/database/Island.java
  src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
  src/main/resources/patch_1.sql
  src/main/resources/patch_2_mysql.sql
  src/main/resources/patch_3.sql
Labels: enhancement

#498 Add price abbreviations to the shop
  src/main/java/com/iridium/iridiumskyblock/configs/Shop.java
  src/main/java/com/iridium/iridiumskyblock/gui/ShopCategoryGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/ShopOverviewGUI.java
Labels: enhancement

#490 Add check itemframe when breaking
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
Labels: bug

#502 Fixed Upgrading Databases
  src/main/java/com/iridium/iridiumskyblock/DataConverter.java
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/ForeignIslandTableManager.java
  src/main/resources/patch_3.sql
Labels: bug, enhancement

#501 Add extravalue placeholder
  src/main/java/com/iridium/iridiumskyblock/configs/Placeholders.java
  src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
Labels: enhancement

#508 Fixed Bug Crops Mine Mission
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
Labels: bug

#510 Fixed Issues with Daily Island Missions
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: bug

#511 Remove Ori from the issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#509 Fix Possible NullPointerException
  src/main/java/com/iridium/iridiumskyblock/utils/PlayerUtils.java
Labels: bug

#507 Optimised Saving Data
  src/main/java/com/iridium/iridiumskyblock/DatabaseObject.java
  src/main/java/com/iridium/iridiumskyblock/database/Island.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBank.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBlocks.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBooster.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandData.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandMission.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandPermission.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandSetting.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandSpawners.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandUpgrade.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandWarp.java
  src/main/java/com/iridium/iridiumskyblock/database/User.java
  src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/TableManager.java
Labels: enhancement

#514 Fix the permission gui pagination
  src/main/java/com/iridium/iridiumskyblock/gui/IslandPermissionsGUI.java
Labels: bug

#516 Fix permissions GUI pagination again
  src/main/java/com/iridium/iridiumskyblock/gui/IslandPermissionsGUI.java
Labels: bug

#519 Fix mobs targeting visitors when they shouldn't
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityTargetListener.java
Labels: bug

#520 Fix mob targeting when there are only guests
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityTargetListener.java
Labels: bug
