Repository Iridium-Development/IridiumSkyblock, pull requests merged in 2021-05, with the labels that each got.

#61 Add Ocean generator, Improve Skyblock generator
  plugin/src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  plugin/src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
  plugin/src/main/java/com/iridium/iridiumskyblock/generators/GeneratorType.java
  plugin/src/main/java/com/iridium/iridiumskyblock/generators/OceanGenerator.java
Labels: documentation, enhancement

#62 Improve the build process
  plugin/build.gradle.kts
Labels: enhancement

#65 Improve the Github Actions workflow
  .github/workflows/gradle.yml
Labels: enhancement

#71 Bump OrmLite to beta version
  plugin/build.gradle.kts
Labels: enhancement

#72 Fix MVdWPlaceholderAPI dependency
  plugin/build.gradle.kts
Labels: bug

#73 Fix schematic shrinking
  plugin/src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
Labels: bug

#74 Cleanup schematic code
  plugin/src/main/java/com/iridium/iridiumskyblock/Schematic.java
  plugin/src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
Labels: enhancement

#78 Make cleardata command send a success message
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/ClearDataCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/configs/Inventories.java
Labels: bug

#80 Potential fix of java.lang.IllegalArgumentException
  plugin/src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: bug, help wanted

#84 Add number abbreviations
  plugin/src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
  plugin/src/main/java/com/iridium/iridiumskyblock/database/Island.java
  plugin/src/main/java/com/iridium/iridiumskyblock/placeholders/ClipPlaceholderAPI.java
  plugin/src/main/java/com/iridium/iridiumskyblock/placeholders/MVDWPlaceholderAPI.java
  plugin/src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
  plugin/src/main/java/com/iridium/iridiumskyblock/utils/NumberFormatter.java
Labels: enhancement

#79 Add island shop
  plugin/src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/ShopCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/configs/Commands.java
  plugin/src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  plugin/src/main/java/com/iridium/iridiumskyblock/configs/Shop.java
  plugin/src/main/java/com/iridium/iridiumskyblock/gui/ShopCategoryGUI.java
  plugin/src/main/java/com/iridium/iridiumskyblock/gui/ShopOverviewGUI.java
  plugin/src/main/java/com/iridium/iridiumskyblock/shop/ShopCategory.java
  plugin/src/main/java/com/iridium/iridiumskyblock/shop/ShopItem.java
  plugin/src/main/java/com/iridium/iridiumskyblock/shop/ShopManager.java
  plugin/src/main/java/com/iridium/iridiumskyblock/utils/PlayerUtils.java
Labels: enhancement

#82 Fix ocean generator regeneration issues
  plugin/src/main/java/com/iridium/iridiumskyblock/generators/OceanGenerator.java
  plugin/src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: bug

#85 Cleanup the configs
  plugin/src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  plugin/src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
  plugin/src/main/java/com/iridium/iridiumskyblock/bank/MoneyBankItem.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/BankCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/BoostersCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/BorderCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/DeleteCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/DeleteWarpCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/DemoteCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/DepositCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/EditWarpCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/HomeCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/InfoCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/InviteCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/KickCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/LeaveCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/LogsCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/MembersCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/MissionCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/PermissionsCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/PrivateCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/PromoteCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/PublicCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/RegenCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/RewardsCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/SetHomeCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/SetWarpCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/ShopCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/TransferCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/TrustCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/UnInviteCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/UnTrustCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/UpgradesCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/ValueCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/VisitCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/WarpsCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/commands/WithdrawCommand.java
  plugin/src/main/java/com/iridium/iridiumskyblock/configs/Boosters.java
  plugin/src/main/java/com/iridium/iridiumskyblock/configs/Commands.java
  plugin/src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  plugin/src/main/java/com/iridium/iridiumskyblock/gui/IslandRegenGUI.java
Labels: enhancement

#97 Clear Inventories
  plugin/src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
  plugin/src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: enhancement

#101 Fix item pickup event for legacy versions
  plugin/src/main/java/com/iridium/iridiumskyblock/listeners/EntityPickupItemListener.java
Labels: bug

#103 Fix ClassNotFoundException for MultiVersion code on HotSpot VM
  plugin/src/main/java/com/iridium/iridiumskyblock/multiversion/MinecraftVersion.java
Labels: bug
