Repository Iridium-Development/IridiumSkyblock, pull requests merged in 2021-10, with the labels that each got.

#409 Fix bank item names being null
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/bank/BankItem.java
Labels: bug

#359 Various code improvements
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/commands/CreateCommand.java
  src/main/java/com/iridium/iridiumskyblock/gui/BankGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MembersGUI.java
Labels: enhancement

#400 Add new stuffs
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityDamageListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityTargetListener.java
Labels: bug, enhancement

#413 Add database type to bStats metrics
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
Labels: enhancement

#414 Prevent bypassing players being kicked by private command
  src/main/java/com/iridium/iridiumskyblock/commands/BanCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BypassCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
  src/main/java/com/iridium/iridiumskyblock/commands/ExpelCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/JoinCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PrivateCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/TransferCommand.java
  src/main/java/com/iridium/iridiumskyblock/database/User.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BucketListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerJoinQuitListener.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: bug, enhancement

#416 Add more placeholders
  src/main/java/com/iridium/iridiumskyblock/configs/Placeholders.java
  src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
Labels: enhancement

#415 Add click to join button to invite command
  src/main/java/com/iridium/iridiumskyblock/commands/HelpCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/InviteCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
Labels: enhancement

#419 Add toggle for the island menu
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
  src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
Labels: enhancement

#420 Automatically select schematic if there is only one
  src/main/java/com/iridium/iridiumskyblock/commands/CreateCommand.java
Labels: enhancement

#428 [ci-skip] Update Workflow
  .github/workflows/gradle.yml
Labels: enhancement

#429 Bump IridiumCore to 1.3.2
  build.gradle.kts
Labels: enhancement

#439 Fix ClassCastException
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityDamageListener.java
Labels: bug

#437 Fix weather changing
  src/main/java/com/iridium/iridiumskyblock/IslandWeatherType.java
Labels: bug

#436 Add AsyncWorldEdit
  src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
Labels: enhancement

#423 Make Boosters are stackable
  src/main/java/com/iridium/iridiumskyblock/Booster.java
  src/main/java/com/iridium/iridiumskyblock/commands/BoosterCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Boosters.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBooster.java
Labels: enhancement

#443 Fix mob spawn setting blocking all entities
  src/main/java/com/iridium/iridiumskyblock/listeners/EntitySpawnListener.java
Labels: bug

#477 Fix island ban check
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: bug

#480 Fix entity hooking triggering mission
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerFishListener.java
Labels: bug

#479 Improve command syntax color stripping
  build.gradle.kts
  src/main/java/com/iridium/iridiumskyblock/commands/HelpCommand.java
Labels: enhancement

#481 Fix InvalidPluginException
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
Labels: bug

#483 Increase cooldown times & Fix message spam
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerPortalListener.java
Labels: enhancement

#485 Add spy command
  src/main/java/com/iridium/iridiumskyblock/commands/SpyCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Commands.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/database/User.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerChatListener.java
Labels: enhancement
