Repository Iridium-Development/IridiumSkyblock, pull requests merged in 2021-04, with the labels that each got.

#28 Info command, API improvements, New placeholder format
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
  src/main/java/com/iridium/iridiumskyblock/commands/InfoCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/TransferCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/BankItems.java
  src/main/java/com/iridium/iridiumskyblock/configs/Inventories.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/configs/Permissions.java
  src/main/java/com/iridium/iridiumskyblock/database/Island.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandTopGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/VisitGUI.java
  src/main/java/com/iridium/iridiumskyblock/utils/Placeholder.java
Labels: enhancement

#30 Missions
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/Mission.java
  src/main/java/com/iridium/iridiumskyblock/Reward.java
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
  src/main/java/com/iridium/iridiumskyblock/commands/InfoCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/MissionCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Inventories.java
  src/main/java/com/iridium/iridiumskyblock/configs/Missions.java
  src/main/java/com/iridium/iridiumskyblock/database/Island.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandMission.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandTopGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MissionSelectGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MissionsGUI.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockGrowListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EnchantItemListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityDeathListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/FurnaceSmeltListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/ItemCraftListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerFishListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PotionBrewListener.java
  src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: enhancement

#31 Add /is blockvalues command, Revise GUI fillers
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/commands/BlockValueCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BlockValues.java
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
  src/main/java/com/iridium/iridiumskyblock/configs/BlockValues.java
  src/main/java/com/iridium/iridiumskyblock/configs/Inventories.java
  src/main/java/com/iridium/iridiumskyblock/database/Island.java
  src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/BlockValueSelectGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/ConfirmationGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/GUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/InvitesGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandTopGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MembersGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MissionSelectGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MissionsGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/PermissionsGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/PermissionsRankGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/SchematicGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/VisitGUI.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: enhancement

#32 Unify messages
  src/main/java/com/iridium/iridiumskyblock/commands/AboutCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BankCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BlockValueCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BypassCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/CreateCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/DeleteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/DepositCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/HomeCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/InfoCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/InviteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/LeaveCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/MembersCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/MissionCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PermissionsCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PositionCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PrivateCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PublicCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/RegenCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/ReloadCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/SaveSchematicCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/SetHomeCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/TopCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnInviteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/ValueCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/VisitCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/WithdrawCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Inventories.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/configs/Permissions.java
Labels: enhancement

#36 Reformat some code
  src/main/java/com/iridium/iridiumskyblock/BlockData.java
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/Mission.java
  src/main/java/com/iridium/iridiumskyblock/Permission.java
  src/main/java/com/iridium/iridiumskyblock/Persist.java
  src/main/java/com/iridium/iridiumskyblock/Reward.java
  src/main/java/com/iridium/iridiumskyblock/api/IridiumSkyblockAPI.java
  src/main/java/com/iridium/iridiumskyblock/bank/BankItem.java
  src/main/java/com/iridium/iridiumskyblock/bank/CrystalsBankItem.java
  src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
  src/main/java/com/iridium/iridiumskyblock/bank/MoneyBankItem.java
  src/main/java/com/iridium/iridiumskyblock/commands/AboutCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BankCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BlockValueCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/DemoteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/DepositCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/InviteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/MembersCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/MissionCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PermissionsCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PromoteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/TransferCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/WithdrawCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/BlockValues.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBank.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBlocks.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandInvite.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandMission.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandPermission.java
  src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandCreateGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandTopGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MissionSelectGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/MissionsGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/PermissionsGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/VisitGUI.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BucketListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityDamageListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerDropItemListener.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
  src/main/java/com/iridium/iridiumskyblock/nms/NMS.java
  src/main/java/com/iridium/iridiumskyblock/nms/v1_16_R3.java
Labels: documentation, enhancement

#37 Add SSL support
  src/main/java/com/iridium/iridiumskyblock/configs/SQL.java
  src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
Labels: bug, enhancement

#38 Improve schematic shrinking
  src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
Labels: enhancement

#41 Update to Gradle 7.0
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#43 Start relocating all relevant dependencies
  build.gradle.kts
Labels: enhancement

#51 Fix the sql connection string
  src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
Labels: bug
