Repository Iridium-Development/IridiumSkyblock, pull requests merged in 2021-06, with the labels that each got.

#110 Fix shop rounding issues
  src/main/java/com/iridium/iridiumskyblock/shop/ShopManager.java
Labels: bug, documentation

#109 Make Gradle build script more readable
  build.gradle.kts
Labels: documentation, enhancement

#119 Member Upgrade and new placeholders
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/PlaceholderBuilder.java
  src/main/java/com/iridium/iridiumskyblock/commands/InviteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/JoinCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/configs/Upgrades.java
  src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
  src/main/java/com/iridium/iridiumskyblock/upgrades/MemberUpgrade.java
Labels: enhancement

#124 Add config to Respawn on island
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerRespawnListener.java
Labels: enhancement

#136 Fix reload not affecting shop categories
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/shop/ShopManager.java
Labels: bug

#141 Fix PAPI reload issues
  src/main/java/com/iridium/iridiumskyblock/placeholders/ClipPlaceholderAPI.java
Labels: enhancement

#144 1.17 support
  build.gradle.kts
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
  src/main/java/com/iridium/iridiumskyblock/shop/ShopManager.java
Labels: enhancement

#149 Make the island ranks configurable
  src/main/java/com/iridium/iridiumskyblock/commands/PermissionsCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Inventories.java
  src/main/java/com/iridium/iridiumskyblock/configs/inventories/IslandRanksInventoryConfig.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandRanksGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/PermissionsRankGUI.java
Labels: enhancement

#151 Relocate the update checker
  build.gradle.kts
Labels: bug, documentation, enhancement

#150 Add ability to change the island name
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
  src/main/java/com/iridium/iridiumskyblock/commands/RenameCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Commands.java
  src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
Labels: enhancement

#157 Further improve the Gradle build process
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#158 Cleanup & Optimise the ore generation, Add stone generators
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockFormListener.java
  src/main/java/com/iridium/iridiumskyblock/utils/RandomAccessList.java
Labels: documentation, enhancement

#163 Fix main command not being executable in console
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
Labels: bug

#173 Border bug fixes and message fixes
  src/main/java/com/iridium/iridiumskyblock/commands/DepositCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/VisitCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/WithdrawCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerRespawnListener.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
  src/main/java/com/iridium/iridiumskyblock/utils/PlayerUtils.java
Labels: bug, enhancement

#187 Fix item of cactus quest
  src/main/java/com/iridium/iridiumskyblock/configs/Missions.java
Labels: bug

#186 Fix warp messages & Fix ArrayIndexOutOfBoundsException
  src/main/java/com/iridium/iridiumskyblock/commands/Command.java
  src/main/java/com/iridium/iridiumskyblock/commands/DeleteWarpCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/DemoteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/DepositCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/EditWarpCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/FlyCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/JoinCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/KickCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PromoteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/SetWarpCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnInviteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnTrustCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/WarpsCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/WithdrawCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/subcommands/BankGive.java
  src/main/java/com/iridium/iridiumskyblock/commands/subcommands/BankRemove.java
  src/main/java/com/iridium/iridiumskyblock/commands/subcommands/BankSet.java
Labels: bug, enhancement

#165 Fix islandrewards not being saved on databases with a too small default column width
  src/main/java/com/iridium/iridiumskyblock/database/IslandReward.java
Labels: bug

#162 Added config option for island rank displayname in messages and placeholders
  src/main/java/com/iridium/iridiumskyblock/IslandRank.java
  src/main/java/com/iridium/iridiumskyblock/PlaceholderBuilder.java
  src/main/java/com/iridium/iridiumskyblock/commands/DemoteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PromoteCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
  src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
Labels: enhancement

#215 Change default cookie price
  src/main/java/com/iridium/iridiumskyblock/configs/Shop.java
Labels: bug, enhancement

#220 Fix mission requirements
  src/main/java/com/iridium/iridiumskyblock/configs/Missions.java
Labels: bug

#221 Fix license
  LICENSE
Labels: enhancement
