Repository Iridium-Development/IridiumSkyblock, pull requests merged in 2021-09, with the labels that each got.

#384 Prevent data duplication issues
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/iridium/iridiumskyblock/DataConverter.java
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/commands/BanCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/ExpelCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PrivateCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/TrustCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnBanCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnTrustCommand.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBan.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBank.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBlocks.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandBooster.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandData.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandInvite.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandLog.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandMission.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandPermission.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandReward.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandSpawners.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandTrusted.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandUpgrade.java
  src/main/java/com/iridium/iridiumskyblock/database/IslandWarp.java
  src/main/java/com/iridium/iridiumskyblock/database/User.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
  src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/ForeignIslandTableManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/IslandTableManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/TableManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/UserTableManager.java
  src/main/resources/patch_1.sql
Labels: bug, enhancement

#387 Refactored Commands to make Ori Happy
  src/main/java/com/iridium/iridiumskyblock/IslandRank.java
  src/main/java/com/iridium/iridiumskyblock/commands/BanCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BankCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BlockValueCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BoostersCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/BorderCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/ChatCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/ClearDataCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/Command.java
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
  src/main/java/com/iridium/iridiumskyblock/commands/DeleteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/DeleteWarpCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/DemoteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/DepositCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/EditWarpCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/ExpelCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/FlyCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/InfoCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/InviteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/JoinCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/KickCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/LeaveCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/LevelCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/LogsCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/MembersCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/MissionCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PermissionsCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PrivateCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PromoteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/PublicCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/RecalculateCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/RegenCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/RenameCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/RewardsCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/SetHomeCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/SetWarpCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/TransferCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/TrustCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnBanCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnInviteCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UnTrustCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/UpgradesCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/ValueCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/VisitCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/WarpsCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/WithdrawCommand.java
  src/main/java/com/iridium/iridiumskyblock/gui/ConfirmationGUI.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: enhancement

#403 Fix Withdrawing if inventory is full.
  src/main/java/com/iridium/iridiumskyblock/shop/ShopManager.java
  src/main/java/com/iridium/iridiumskyblock/utils/PlayerUtils.java
Labels: bug, Verified

#405 Fix Bug : Prevent item crafting with Island Crystals.
  src/main/java/com/iridium/iridiumskyblock/listeners/ItemCraftListener.java
Labels: bug

#397 Send chunks after biomes changed
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: bug

#401 Change height schematic Island
  src/main/java/com/iridium/iridiumskyblock/configs/Schematics.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
  src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
Labels: bug

#392 Made Bank Items' names in messages configurable and added message for crystal deposit
  src/main/java/com/iridium/iridiumskyblock/bank/BankItem.java
  src/main/java/com/iridium/iridiumskyblock/bank/CrystalsBankItem.java
  src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
  src/main/java/com/iridium/iridiumskyblock/bank/MoneyBankItem.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
Labels: enhancement
