Repository Iridium-Development/IridiumSkyblock, pull requests merged in 2022-03, with the labels that each got.

#624 Add 1.18.2 support & Update dependencies
  build.gradle.kts
Labels: enhancement

#628 Fix is visit with isBypassing
  src/main/java/com/iridium/iridiumskyblock/gui/VisitGUI.java
Labels: bug

#629 Update Github workflow
  .github/workflows/gradle.yml
Labels: enhancement

#612 Fix command execution for subcommands in camelCase
  src/main/java/com/iridium/iridiumskyblock/commands/Command.java
Labels: bug

#631 Fix #564
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
Labels: bug

#621 Change how users bypass island privacy
  src/main/java/com/iridium/iridiumskyblock/api/IridiumSkyblockAPI.java
  src/main/java/com/iridium/iridiumskyblock/commands/VisitCommand.java
  src/main/java/com/iridium/iridiumskyblock/database/Island.java
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerTeleportListener.java
Labels: documentation, enhancement, api

#636 Fix top island placeholder
  src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
Labels: bug

#638 WorldEdit incompatibility check
  src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
  src/main/java/com/iridium/iridiumskyblock/schematics/WorldEdit.java
Labels: bug, enhancement

#617 Improve speed of ocean generator recalculation
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/api/IridiumSkyblockAPI.java
  src/main/java/com/iridium/iridiumskyblock/generators/GeneratorType.java
  src/main/java/com/iridium/iridiumskyblock/generators/IridiumChunkGenerator.java
  src/main/java/com/iridium/iridiumskyblock/generators/OceanGenerator.java
  src/main/java/com/iridium/iridiumskyblock/generators/SkyblockGenerator.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: documentation, enhancement, api
