Repository Iridium-Development/IridiumSkyblock, pull requests merged in 2022-02, with the labels that each got.

#594 Fix 1.18 ocean generation
  src/main/java/com/iridium/iridiumskyblock/generators/OceanGenerator.java
Labels: bug

#598 Fix y coordinate in currentOffset command
  src/main/java/com/iridium/iridiumskyblock/commands/home/CurrentOffsetCommand.java
Labels: bug

#597 Remove unused TriFunction interface
  src/main/java/com/iridium/iridiumskyblock/utils/TriFunction.java
Labels: enhancement

#599 Increase default money withdrawal amount
  src/main/java/com/iridium/iridiumskyblock/configs/BankItems.java
Labels: enhancement

#593 Fix explosions being able to happen on foreign islands
  src/main/java/com/iridium/iridiumskyblock/listeners/EntityExplodeListener.java
Labels: bug

#575 Add Nullable User#getPlayer() User#toPlayer()
  src/main/java/com/iridium/iridiumskyblock/database/User.java
Labels: enhancement, api

#568 Fix issue with +54 rewards
  src/main/java/com/iridium/iridiumskyblock/gui/IslandRewardsGUI.java
Labels: bug

#595 Add option to disable setting/permission modifications
  src/main/java/com/iridium/iridiumskyblock/Permission.java
  src/main/java/com/iridium/iridiumskyblock/Setting.java
  src/main/java/com/iridium/iridiumskyblock/configs/IslandSettings.java
  src/main/java/com/iridium/iridiumskyblock/configs/Permissions.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandPermissionsGUI.java
  src/main/java/com/iridium/iridiumskyblock/gui/IslandSettingsGUI.java
Labels: enhancement

#596 Add command to delete other islands
  src/main/java/com/iridium/iridiumskyblock/api/IslandDeleteEvent.java
  src/main/java/com/iridium/iridiumskyblock/commands/DeleteCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
Labels: enhancement

#603 Add shift support to the bank
  src/main/java/com/iridium/iridiumskyblock/gui/IslandBankGUI.java
Labels: enhancement

#602 Improve IridiumSkyblockAPI class
  src/main/java/com/iridium/iridiumskyblock/api/IridiumSkyblockAPI.java
Labels: documentation, enhancement, api

#601 Add weight to the mission slots
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: enhancement

#604 Fix mission slot NullPointerException
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: bug

#613 Fix default schematic offsets
  src/main/java/com/iridium/iridiumskyblock/configs/Schematics.java
Labels: bug

#614 Optimization Position Verification.
  src/main/java/com/iridium/iridiumskyblock/database/Island.java
Labels: enhancement
