Repository Iridium-Development/IridiumSkyblock, pull requests merged in 2022-01, with the labels that each got.

#548 Fix ClassCastException for most hanging entities
  src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
Labels: bug

#546 Fix fire ticks harming visitors
  src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
Labels: bug

#549 Fix SQL patch 4
  src/main/resources/patch_4.sql
Labels: bug

#554 Fix empty subcommand list in help command
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/iridium/iridiumskyblock/commands/HelpCommand.java
Labels: bug

#555 Add DoctaEnkoda to the list of contributors
  src/main/java/com/iridium/iridiumskyblock/commands/AboutCommand.java
Labels: enhancement

#556 Update dependencies
  build.gradle.kts
  src/main/java/com/iridium/iridiumskyblock/managers/TestingDao.java
  src/main/java/com/iridium/iridiumskyblock/support/RoseStackerSupport.java
Labels: bug, enhancement

#569 Change deprecated method
  src/main/java/com/iridium/iridiumskyblock/listeners/BucketListener.java
Labels: enhancement

#563 Disable Task start if multiverse is not on server
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
Labels: enhancement

#562 Negative value for disable task island recalculate
  src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
Labels: enhancement

#560 Add CurrentOffset command
  src/main/java/com/iridium/iridiumskyblock/commands/HomeCommand.java
  src/main/java/com/iridium/iridiumskyblock/commands/home/CurrentOffsetCommand.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
Labels: enhancement

#565 Implement crystal depositing via Island bank
  src/main/java/com/iridium/iridiumskyblock/bank/CrystalsBankItem.java
  src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
  src/main/java/com/iridium/iridiumskyblock/bank/MoneyBankItem.java
  src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
Labels: enhancement

#567 Fix subcommands appearing in tabcompletion without permissions
  src/main/java/com/iridium/iridiumskyblock/commands/Command.java
  src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
Labels: bug

#566 Fix right-clicking depositing two crystals at once
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
Labels: bug

#572 Fix Crystal Item Place
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
Labels: bug

#577 Optimize something
  src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
Labels: enhancement

#579 Delete IslandSetting to Database + Clean Code
  src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Labels: enhancement

#591 Fix rename command colorization
  src/main/java/com/iridium/iridiumskyblock/commands/RenameCommand.java
Labels: bug
